# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgmtApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacherClass',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(to='studentMgmtApp.Class'),
        ),
    ]
