# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgmtApp', '0002_auto_20160729_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.TextField(max_length=30)),
                ('testDate', models.DateField()),
                ('testClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMgmtApp.Class')),
                ('testTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentMgmtApp.Teacher')),
            ],
        ),
    ]
